development:
  adapter: postgresql
  encoding: unicode
  database: klog_development
  pool: 5
  username: rails
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: klog_test
  pool: 5
  username: rails
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: klog_production
  pool: 5
  username: klog
  password: 
