# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebc9d971342bca347ea17b46e5864f0be85f6075d7194e4454e064f0f7628dd1a864f99dceba5031d7130705eb95947759523e20cf34ab11513090d731eab99f

test:
  secret_key_base: 4b3a53377d68b849d29c46ed36d1a4f50cb9d3976ba661951451f8355bae66a50f9efa3121d7b68e23f6d986a5a7da2f4e0e0511ee2d919a037bac3756695c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
